### ISSUE TITLE
add premium client functionality

### ISSUE THREAD

**Issue by Japoivvb** [nsaladie/MP03_POO_Shop#1]
1. before ask for client name in sale option, include a new question about if the client is premium or not.

-    if the answer is No, continue flow as is

-    if the answer is Yes, 

       create a premiumClient object which extends from Client, 
	   it has a points attribute and its pay method is the same as parent client but for each 10€ sales, it adds 1 point. e.g. if sale 35€, premiumClient gets 3 points.
       show its points earned after the sale total amount
	   
2. set issue label as enhancement to be tracked

3. commit message with verb + #numberIssue + details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by nsaladie** [comment]
### The issue has been fixed and new code pushed to main branch.

**Commit:**

> ![image](https://github.com/nsaladie/MP03_POO_Shop/assets/163297072/79e291f9-d6b3-4fc7-b9c6-7db4662ae801)

**Upgrade Code:**

> ![image](https://github.com/nsaladie/MP03_POO_Shop/assets/163297072/994a69be-7f95-4b9a-bc8d-2d1141fee748)


**Sale of a premium client:**

> ![image](https://github.com/nsaladie/MP03_POO_Shop/assets/163297072/36ca880f-c955-483a-a937-d4328a8fca72)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
great job, you got +1 in UF4P1
