### ISSUE TITLE
dao layer should not throw any SQL exception, they must be handled in each implementation class

### ISSUE THREAD

**Issue by Japoivvb** [nsaladie/MP03_POO_Shop#5]
https://github.com/nsaladie/MP03_POO_Shop/blob/623f9d16b64c47e192811347386c7e1448bea5bd/src/dao/Dao.java#L10

**Comment by nsaladie** [comment]
The issue has been fixed and new code pushed to main branch.

**Commit:**
> ![image](https://github.com/user-attachments/assets/66a663aa-c53d-4879-886d-7c60413f8df4)

** Upgrade Code: **
> ![image](https://github.com/user-attachments/assets/555564f6-6ecd-4c7b-98bd-80789a899db7)
> ![image](https://github.com/user-attachments/assets/68f0f3e8-a7c3-471b-93e6-f2fd360c67b4)

**Comment by nsaladie** [comment]
The issue has been fixed and new code pushed to main branch.

**Comits:**
> ![image](https://github.com/user-attachments/assets/02cc95cb-d2fa-41a2-8cf4-91a25185f9a3)

**Upgrade Code:**
> ![image](https://github.com/user-attachments/assets/a1db025e-ddd9-4e2f-b542-590b7dc87871)
